### PR TITLE
Fix #9393

### LINKED ISSUE #9393: WebAssembly trap: An arithmetic exception after mainnet and testnet upgrade
## Describe the bug

We experienced failures in the wasm runtiem, which can be related to the recent mainnet upgrade. The particular exception happens, in our case, during ed25519 signature verification. The part which panics is during the hash computation: https://github.com/dalek-cryptography/ed25519-dalek/blob/1.0.1/src/public.rs#L344
Exception:

```text
ExecutionError: 'WebAssembly trap: An arithmetic exception, e.g. divided by zero.'
```

It was reported that it was in the testnet for more than a week.

### Bug history

In the summary, to repeat what is the latest knowledge of the issue:
* first experienced in July 18 in the testnet
* first experienced in mainnet on August 1
* by digging into the issue, I was able to find the exact place where it fails: hashing the claim (sha512) in the ed25519-delek lib. Same happens in near_crypto
* I replicated the scenario in unit tests and workspace , but in contrast to mainnet and testnet, it works, the code works in the unit tests and workspace.
* I setup other contracts on tesnet and they also fail

Dates of the issue when they first appeared 

* first experienced on July 1 on testnet, the prior transaction is on 6/29 before the upgrade and didn't fail
* first experienced on August 2 on mainnet

**Expected behavior**

It worked in during the past months, and now it panics. It should just work.

**Example transaction**
https://explorer.near.org/transactions/7LrhUybXfyD5CXHRahyNgPCW3qw8NWUuxQwXH87fxL2

**Version (please complete the following information):**
- nearcore: near mainnet
- rust version: 1.69
- near-sdk: 4.1.1

### PR DESCRIPTION
**Pull request by nagisa**
We made a single letter mistake and passed values larger than `i32::MAX` to a function that did only supports `0..=i32::MAX`. This fix corrects the problem, introduces the necessary protocol versioning, a regression test and an additional assert to validate the inputs in the aforementioned function.

I ended up using the parameters for the behaviour flag in anticipation that I wouldn’t need to do this later as part of https://github.com/near/nearcore/pull/9364.

### CODE REVIEW

File: runtime/near-vm/compiler-singlepass/src/codegen_x64.rs [hunk 1]
```diff
@@ -349,14 +349,26 @@ impl<'a> FuncGen<'a> {
...
     fn emit_gas_const(&mut self, cost: u64) {
-        if let Ok(cost) = u32::try_from(cost) {
-            self.emit_gas(Location::Imm32(cost));
+        if self.config.disable_9393_fix {
+            // emit_gas only supports Imm32 with an argument up-to i32::MAX, but we made *this*
+            // single-letter oversight at some point & the bug made its way into mainnet. Now that
+            // we need to maintain backwards compatibility and replayability of the old
+            // transactions, we end up with this wonderful and slightly horrifying monument to our
+            // former selves :)
+            if let Ok(cost) = u32::try_from(cost) {
```
Comment (jakmeier) [inline runtime/near-vm/compiler-singlepass/src/codegen_x64.rs:358]: well written :D

File: runtime/near-vm/compiler-singlepass/src/codegen_x64.rs [hunk 2]
```diff
@@ -365,10 +377,12 @@ impl<'a> FuncGen<'a> {
...
-        assert!(
-            matches!(cost_location, Location::Imm32(_) | Location::GPR(_)),
-            "emit_gas can take only an imm32 or a gpr argument"
-        );
+
+        match cost_location {
+            Location::Imm32(v) if v <= i32::MAX as u32 => {}
+            Location::GPR(_) => {}
+            _ => panic!("emit_gas can take only a imm32 < 0xFFF_FFFF or a gpr argument"),
+        }
```
Comment (jakmeier) [inline runtime/near-vm/compiler-singlepass/src/codegen_x64.rs:385]: I guess this needs feature flagging to avoid the unfixed version from panicking.

(Unless you want o change the `emit_gas_cons` to reproduce the bug in other ways, like manually sign extending to a GPR or something along those lines... which sounds horrifying.)

File: runtime/near-vm-runner/src/tests/runtime_errors.rs [hunk 3]
```diff
@@ -1059,3 +1059,30 @@ mod fix_contract_loading_cost_protocol_upgrade {
...
+            VMOutcome: balance 4 storage_usage 12 return data None burnt gas 100000000000000 used gas 100000000000000
+            Err: Exceeded the maximum amount of gas allowed to burn per contract.
+        "#]],
+    ]);
+    after_builder.wasm(&contract).expects(&[
+        expect![[r#"
+            VMOutcome: balance 4 storage_usage 12 return data None burnt gas 2763981177 used gas 2763981177
+        "#]],
+    ]);
+}
```
Comment (jakmeier) [inline runtime/near-vm-runner/src/tests/runtime_errors.rs:1088]: yes this test looks much better now :+1:

**Review by jakmeier — COMMENTED** [review]
Apart from the new assertion that shouldn't trigger on the old paths, this looks good to me. Thanks for quickly coming up with a clean implementation, including a proper tests!

(The new test also catches the assertion issue in CI, so good confirmation that it's doing what it's supposed to do.)

**Comment by jakmeier** [comment]
> Complication: there are multiple things in the upcoming protocol version 63. When backporting we will need to bump the protocol version for BlockHeaderV4 to 64...

Oh, I see. The current release candidate for [1.36.0](https://github.com/ppca/nearcore/tree/1.36.0), which isn't quite on testnet yet, has protocol version 63 and includes `BlockHeaderV4`. Mainnet clients (binary 1.35) are at protocol version 62.

I guess we have at least two options:
- what you suggest: backport a fix to 1.35. release 1.35.1 to mainnet and make it protocol version 63, then 1.36 needs to be pushed to protocol version 64
- include both `BlockHeaderV4` and `Disable9393Fix` in protocol version 63 and release it to testnet as 1.36.0, don't release a new mainnet patch release

As I understood the Zulip discussion, it sounded more like the node team only wants to inlcude it in 1.36.0, without a 1.35.1. Which is the second option. This delays the time until the fix is in mainnet (by ~5 weeks I think?), but it allows the normal process to go through.

In any case, it seems this PR is ready as-is, with the protocol version set to 63. If we decide to backport, we should take care of it in separate PRs.

(the snapshot for `test_json_unchanged` needs updating though)
