### PR TITLE
fix: proper flat storage deltas removal

### LINKED ISSUE #8655: Proper deletion of FlatStateDeltas
We've discovered that FlatStateDeltas size is 200MB on live mainnet node, though only 20 of them are actively being changed - which means that we forget to remove some deltas, probably during migration.

Also DB ops trace show that there are more deletions than insertions https://github.com/near/nearcore/issues/8006#issuecomment-1448183752

### PR DESCRIPTION
**Pull request by Longarithm**
Proper deltas removal during flat storage creation and normal operation. Resolves #8655.

The original issue was that we removed deltas exactly twice. It was already resolved around https://github.com/near/nearcore/pull/8683. Reason: we cached blocks and deltas separately, and flat head was cached whereas flat head delta was not - as we don't need it. But we still iterated over all blocks during GC and executed `store_helper::remove_delta` for each block hash. This means that `remove_delta` was called twice: 1) when we move TO flat head; 2) when we move FROM flat head.

Now we call `get_all_deltas_metadata` on flat storage creation, guarantee that all cached deltas exist, and iterate over existing metadatas, not blocks.

However, now we need to GC deltas created during background creation. We do it in two steps:
1) once we caught up single block - its delta is not needed
2) when we create FS object - there can be some fork blocks remaining. We don't even want to load deltas for them anytime, so it's better do to cleanup right now. Theoretical estimation on their metadatas size is fairly small, and in practice we have 2-10 such blocks - so this step is actually needed. After cleanup, on my experiments there were only 2 deltas remaining on DB, as expected.

Side fix: tests revealed that when flat storage is removed, we don't remove deltas and it's better to do it.

At the same time I introduce `CACHED_CHANGES_LIMIT` and `CACHED_CHANGES_SIZE_LIMIT` to warn users that there is too much data cached in flat storage.

## Testing

Adjusting `test_flat_storage_creation_sanity` to check that behaviour: create fork block in the meantime; check in logs that it is actually GC-d; check that previous behaviour fails the test.

### CODE REVIEW

File: core/store/src/flat/store_helper.rs [hunk 1]
```diff
@@ -82,6 +82,14 @@ pub fn remove_delta(store_update: &mut StoreUpdate, shard_uid: ShardUId, block_h
     store_update.delete(FlatStateColumn::DeltaMetadata.to_db_col(), &key);
 }
 
+pub fn remove_all_deltas(store_update: &mut StoreUpdate, shard_uid: ShardUId) {
+    let key_from = shard_uid.to_bytes();
+    let mut key_to = key_from;
+    key_to[7] += 1;
```
Comment (pugachAG) [inline core/store/src/flat/store_helper.rs:88]: what if `key_to[7]` is `u8::MAX_VALUE`? 
I suggest implementing `fn next_shard_prefix(cur: &[u8]) -> Vec<u8>` function which does `+1` with proper carry over handling. Then we can re-used it for flat state removal as well.

File: core/store/src/flat/storage.rs [hunk 2]
```diff
@@ -98,6 +98,12 @@ impl FlatStorageInner {
 }
 
 impl FlatStorage {
+    /// Expected limits for in-memory stored changes, under which flat storage must keep working.
+    /// If they are exceeded, warnings are displayed. Flat storage still will work, but its
+    /// performance will slow down, and eventually it can cause OOM error.
+    const CACHED_CHANGES_LIMIT: usize = 50;
```
Comment (pugachAG) [inline core/store/src/flat/storage.rs:104]: Why do we want to track this separately? As far as I understand there is no risk of having more than 50 small deltas cached and producing `warn` in this case is a false-alarm, at least in the context in flat storage. I suggest removing that and only tracking the total size of cached changes.

**Review by pugachAG — CHANGES_REQUESTED** [review]

File: core/store/src/flat/storage.rs (hunk 2 above)
Comment (Longarithm) [reply core/store/src/flat/storage.rs:104]: As far as I remember, there is a risk of node slowdown if there are too many deltas, even if they are small, so it is also worth a warning.

File: chain/chain/src/flat_storage_creator.rs [hunk 3]
```diff
@@ -367,9 +374,38 @@ impl FlatStorageShardCreator {
...
+                        )),
+                    );
+                    store_update.commit()?;
+
+                    // If we reached chain final head, we can finish catchup and finally create flat storage.
                     if flat_head == chain_final_head.last_block_hash {
+                        // GC deltas from forks which could have appeared on chain during catchup.
+                        // Assuming that flat storage creation finishes in < 2 days, all deltas metadata cannot occupy
+                        // more than (Blocks per day = 48 * 60 * 60) * (BlockInfo size = 72) ~= 12.4 MB.
+                        let mut store_update = self.runtime_adapter.store().store_update();
```
[the remark this answers is not in the document]
Comment (Longarithm) [reply chain/chain/src/flat_storage_creator.rs:392]: It's not necessary, but we need to commit store update before creating flat storage, and I think the current logic is easier to understand.

File: core/store/src/flat/store_helper.rs (hunk 1 above)
Comment (Longarithm) [reply core/store/src/flat/store_helper.rs]: I see. There would be no impact because we have < 256 shards, but I don't want it to suddenly fail at some point. Introduced `ShardUId::next_shard_prefix(bytes)` because it makes more sense as slice operation.

Side note: little-endian is quite annoying here, because I can't just increment shard id. Still we can rely on the fact that all shard uids are unique.

File: core/store/src/flat/storage.rs (hunk 2 above)
Comment (pugachAG) [reply core/store/src/flat/storage.rs:104]: Please elaborate on what those risks are. In my understanding the bottleneck is hash map access, but then this value should be much larger: I expect main memory access to be `~100ns` (which is a pessimistic case with processor cache miss). Even assuming we need 2 memory accesses for each hash map access and acceptable flat storage latency is `100us` then we can still support 500 deltas without major performance degradation.
In general I'm against unnecessary tracking/warn because it introduces maintenance overhead for the future. If you insist on keeping that then please make sure to write an elaborate comment describing calculation behind the value as well as what could happen when we exceed it. For example current comment `eventually it can cause OOM error.` behind `CACHED_CHANGES_LIMIT` is very misleading, because that is only applicable to `CACHED_CHANGES_SIZE_LIMIT`

File: core/store/src/flat/storage.rs [hunk 4]
```diff
@@ -283,6 +291,15 @@ impl FlatStorage {
             block_hash,
             CachedFlatStateDelta { metadata: delta.metadata, changes: Arc::new(cached_changes) },
         );
+        let cached_changes_num_items = guard.metrics.cached_changes_num_items.get() as usize;
```
Comment (pugachAG) [inline core/store/src/flat/storage.rs:294]: please don't use prometheus metrics data source, that is super hacky :) use `cached_changes.len()` and `cached_changes.total_size()` instead

File: chain/chain/src/flat_storage_creator.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (pugachAG) [reply chain/chain/src/flat_storage_creator.rs:392]: OK, let's keep it like that for now, anyway I'm planning refactoring flat storage creator, so I will move that code around later

**Review by pugachAG — CHANGES_REQUESTED** [review]

File: core/store/src/flat/storage.rs (hunk 2 above)
Comment (pugachAG) [reply core/store/src/flat/storage.rs:104]: ah, looks like @jakmeier has just proven me wrong: https://github.com/near/nearcore/issues/8006#issuecomment-1473621334 and we can reasonable support around only around 100 deltas 😞

Comment (Longarithm) [reply core/store/src/flat/storage.rs:104]: Tbh I didn't know exact numbers, but now I can happily add them to comments

Comment (pugachAG) [reply core/store/src/flat/storage.rs:104]: Let's keep it at `100` and add a link to Jakob's table in the comment

File: core/store/src/flat/storage.rs (hunk 4 above)
Comment (Longarithm) [reply core/store/src/flat/storage.rs]: Btw this line was even wrong. I wanted to count number of deltas, not number of items in them - fixed.

**Review by pugachAG — APPROVED** [review]
`update_delta_metrics` is pretty neat!
overall LGTM, thanks for addressing my comments.
