### PR TITLE
Fix ViewClient::GetExecutionOutcome to work with sharding upgrade

### LINKED ISSUE #4977: Fix ViewClient::GetExecutionOutcome
Currently, the handler of `GetExecutionOutcome` returns outcome of an execution and the root proof that this outcome is confirmed by a following block. Each chunk header in a block includes the outcome root of outcomes produced in the previous chunk and the block header includes the root hash of all outcome roots from all chunks included in this block. Therefore, after a block process a receipt or transaction, its outcome is confirmed by the first block that includes a new chunk for the shard that originally processes the transaction/receipt, because a merkle proof can be generated to prove that the outcome is included in the outcome_root of that block. 

This is exactly what `GetExecutionOutcome` needs to do. It needs to find the first block with a new chunk for the shard that the outcome is generated. There are two issues with the current implementation

1) it does not take into account the fact that the number of shards may change between the block where the execution is performed and the block that outcome_root is included.
2) It looks for the next block with new chunk through two database columns `ColNextBlockWithNewChunk` and `ColLastBlockWithNewChunk `. These two columns assume a linear relationship between blocks, but they are updated when all blocks are processed, so they will not work when there are forks.

### PR DESCRIPTION
**Pull request by mzhangmzz**
fixes #4977 

Test plan:
- Modified sharding upgrade test to test `get_next_block_hash_with_new_chunk`, which is used by GetExecutionOutcome
- Existing CI and nayduck tests on GetExeuctionOutcome

### CODE REVIEW

File: chain/chain/src/chain.rs [hunk 1]
```diff
@@ -2542,8 +2542,46 @@ impl Chain {
...
+                            next_shard_layout.get_split_shards(id).unwrap_or_else(|| {
+                                panic!("invalid shard layout {:?} because it does not contain split shards for parent shard {}", next_shard_layout, id)
+                            })
+                        })
+                        .collect::<Vec<_>>()
+                        .into_iter()
+                        .map(|shard_uid| shard_uid.shard_id())
+                        .collect();
+
+                    shard_layout = next_shard_layout;
```
Comment (bowenwang1996) [inline chain/chain/src/chain.rs:2569]: It seems that we have similar logic in some other places. Could we consider refactor this part into its own function?

File: chain/chain/src/chain.rs [hunk 2]
```diff
@@ -2542,8 +2542,46 @@ impl Chain {
         &mut self,
         block_hash: &CryptoHash,
         shard_id: ShardId,
-    ) -> Result<Option<&CryptoHash>, Error> {
-        self.store.get_next_block_hash_with_new_chunk(block_hash, shard_id)
+    ) -> Result<Option<(CryptoHash, ShardId)>, Error> {
```
Comment (bowenwang1996) [inline chain/chain/src/chain.rs:2545]: Could we update the comment for this function to include what it does when the number of shards changes?

**Review by bowenwang1996 — COMMENTED** [review]
It might be helpful to include an end-to-end test that checks transaction status from rpc.

File: chain/chain/src/chain.rs [hunk 3]
```diff
@@ -2542,8 +2542,46 @@ impl Chain {
...
+                let next_shard_layout = self.runtime_adapter.get_shard_layout(&next_epoch_id)?;
+                if next_shard_layout != shard_layout {
+                    shard_ids = shard_ids
+                        .into_iter()
+                        .flat_map(|id| {
+                            next_shard_layout.get_split_shards(id).unwrap_or_else(|| {
+                                panic!("invalid shard layout {:?} because it does not contain split shards for parent shard {}", next_shard_layout, id)
+                            })
+                        })
+                        .collect::<Vec<_>>()
```
Comment (mm-near) [inline chain/chain/src/chain.rs:2564]: nit: can this cause duplicates in the vector ? 

(only if we allow shards to be merged - not sure if we do).

File: integration-tests/tests/client/sharding_upgrade.rs [hunk 4]
```diff
@@ -179,6 +179,55 @@ impl TestShardUpgradeEnv {
         }
     }
 
+    fn check_next_block_with_new_chunk(&mut self, height: BlockHeight) {
```
Comment (mm-near) [inline integration-tests/tests/client/sharding_upgrade.rs:182]: add comment

File: integration-tests/tests/client/sharding_upgrade.rs [hunk 5]
```diff
@@ -179,6 +179,55 @@ impl TestShardUpgradeEnv {
...
+        let block = self.env.clients[0].chain.get_block_by_height(height).unwrap().clone();
+        let block_hash = block.hash();
+        let num_shards = block.chunks().len();
+        for shard_id in 0..num_shards {
+            let mut last_block_hash_with_empty_chunk = match self.env.clients[0]
```
Comment (mm-near) [inline integration-tests/tests/client/sharding_upgrade.rs:187]: nit: this name (last_block_hash_with_empty_chunk) is not necesarily true, as it might be equal to block_hash..

File: integration-tests/tests/client/sharding_upgrade.rs [hunk 6]
```diff
@@ -179,6 +179,55 @@ impl TestShardUpgradeEnv {
...
+                    .unwrap()
+                    .clone();
+                let chunks = last_block.chunks();
+                if chunks.len() == num_shards {
+                    assert_ne!(
+                        chunks.get(shard_id).unwrap().height_included(),
+                        last_block.header().height()
+                    );
+                } else {
+                    for chunk in chunks.iter() {
```
Comment (mm-near) [inline integration-tests/tests/client/sharding_upgrade.rs:222]: this is a little bit unexpected (as you assume here that the block has no chunks at all, right?)

maybe add a comment

File: chain/chain/src/chain.rs (hunk 3 above)
Comment (mzhangmzz) [reply chain/chain/src/chain.rs:2564]: Yes, in the case of shards merging, this won't work. In fact, I didn't consider shard merging when I designed the shard layout API (you can tell from the fact that the function is called `split_shards` instead of something else.

File: integration-tests/tests/client/sharding_upgrade.rs (hunk 6 above)
Comment (mzhangmzz) [reply integration-tests/tests/client/sharding_upgrade.rs:222]: A block actually always contain chunks for all shards in the chunks vector. When there is no new chunk for a shard, it simply copies the chunk for this shard from the last block. That's why I'm checking chunk.height_included() != last_block.header().height() here, that means the height that this chunk was included is not equal to the block height, which means the chunk is not included in this block.

File: integration-tests/tests/client/sharding_upgrade.rs (hunk 5 above)
Comment (mzhangmzz) [reply integration-tests/tests/client/sharding_upgrade.rs:203]: I added more comments, hopefully that will make the meaning of this variable more clear.

File: core/primitives/src/shard_layout.rs [hunk 7]
```diff
@@ -104,17 +104,19 @@ impl ShardLayout {
...
     #[inline]
-    pub fn get_split_shards(&self, parent_shard_id: ShardId) -> Option<Vec<ShardUId>> {
+    pub fn get_split_shard_uids(&self, parent_shard_id: ShardId) -> Option<Vec<ShardUId>> {
+        self.get_split_shard_ids(parent_shard_id).map(|shards| {
+            shards.into_iter().map(|id| ShardUId::from_shard_id_and_layout(id, &self)).collect()
+        })
+    }
+
+    #[inline]
+    pub fn get_split_shard_ids(&self, parent_shard_id: ShardId) -> Option<Vec<ShardId>> {
```
Comment (matklad) [inline core/primitives/src/shard_layout.rs:114]: Feels like some methods here don't need to be `#[inline]`.

File: core/primitives/src/shard_layout.rs [hunk 8]
```diff
@@ -104,17 +104,19 @@ impl ShardLayout {
...
         match self {
             Self::V0(_) => None,
             Self::V1(v1) => match &v1.shards_split_map {
                 Some(shards_split_map) => match shards_split_map.get(parent_shard_id as usize) {
```
Comment (matklad) [inline core/primitives/src/shard_layout.rs:118]: no need for this match now: `=> hards_split_map.get(parent_shard_id as usize).cloneds()`

File: core/store/src/db.rs [hunk 9]
```diff
@@ -83,8 +83,8 @@ pub enum DBCol {
     /// `LightClientBlock`s corresponding to the last final block of each completed epoch
     ColEpochLightClientBlocks = 26,
     ColReceiptIdToShardId = 27,
-    ColNextBlockWithNewChunk = 28,
-    ColLastBlockWithNewChunk = 29,
```
Comment (matklad) [inline core/store/src/db.rs:87]: I'd expect to see a comment explaining `_`

File: core/primitives/src/shard_layout.rs (hunk 7 above)
Comment (mzhangmzz) [reply core/primitives/src/shard_layout.rs:114]: I'll clean those up

File: core/store/src/db.rs (hunk 9 above)
Comment (mzhangmzz) [reply core/store/src/db.rs:87]: Hmm actually just took the existing code `_ColTransactionRefCount` as an example. I am not sure what's the right way to delete/deprecate a column from the database

Comment (bowenwang1996) [reply core/store/src/db.rs:87]: Don't think we have a process for that 😅 Feel free to propose something!

File: chain/chain/src/chain.rs (hunk 3 above)
Comment (mzhangmzz) [reply chain/chain/src/chain.rs]: Also, right now, in the constructor, we check that there is no duplicates in the map. https://github.com/near/nearcore/blob/master/core/primitives/src/shard_layout.rs#L68

File: core/store/src/db.rs (hunk 9 above)
Comment (mzhangmzz) [reply core/store/src/db.rs:87]: I did a few things:
1) moved all the deprecated columns to the end of enum so it's easier to see all of them
2) added a database migration to remove data from deprecated columns

I think for now I am just going to keep the deprecated columns still in the database and in the codebase. We may want to drop the column family entirely, but I think that should be in another PR because it's relatively involved and I don't have time right now. I can open an issue for that if you think it's necessary.

**Review by matklad — APPROVED** [review]

File: core/store/src/db.rs (hunk 9 above)
Comment (mzhangmzz) [reply core/store/src/db.rs:87]: I actually revert the change on 2) because some test were broken and I couldn't quickly figure out why. I don't want to spend too much time on this PR right now so I'll just create an issue to track this

**Comment by mzhangmzz** [comment]
> It might be helpful to include an end-to-end test that checks transaction status from rpc.

Agreed. I'll try to see if I can do that quickly. If not, I might just skip that. I think it should be fine because I didn't make much change to the handler of `GetExecutionOutcome,` the main change is on function `get_block_with_new_chunk`

**Review by bowenwang1996 — APPROVED** [review]

**Comment by bowenwang1996** [comment]
@frol @khorolets this PR requires your approval

**Review by mm-near — APPROVED** [review]

**Review by khorolets — APPROVED** [review]

**Review by chefsale — APPROVED** [review]
