### PR TITLE
[Epoch Sync] Fix GC error spam and invalid height problem

### LINKED ISSUE #11930: Header sync incorrectly disregards peers at startup
This is a subtle startup corner case. When starting up,
 - We wait for the number of peers to pass a certain threshold before entering sync, but there is a delay between we pass that threshold and when we actually enter sync.
 - Meanwhile, we may have a peer that sends us a new block
 - We have logic that if we receive a block and we're not syncing, and the block is way too high, we consider the block as invalid and remember the block hash as invalid
 - When we then consider whether we're ready to enter sync, we throw away that peer because the peer's highest block is a known "invalid" block, therefore the peer is not eligible and we have not enough peers.
 - This cycle repeats.

Perhaps it makes sense to add a initial state, instead of NoSync, make it InitializingSync or something, during which we don't ban incoming blocks.

### LINKED ISSUE #11936: [Epoch Sync] Error in gc: DB Not Found Error: BLOCK HEADER: 11111111111111111111111111111111
This gets printed out once a second while the node is doing epoch sync.

### PR DESCRIPTION
**Pull request by robin-near**
* GC prints error because the head is at genesis. Return early in that case. Otherwise while we're doing epoch sync because head remains at genesis, this keeps spamming the logs.
* See #11930 for a header sync problem; a recently received block is marked as invalid because its height is too far ahead of where our head is (genesis). We fix this by not marking blocks as invalid if it's just because of height. The reason why we mark a block as invalid is because we think that the block can never be valid (e.g. due to some state disagreement) so we should not bother trying it again, but if invalid height is the issue, this is counterproductive.

Closes #11930 
Closes #11936

### CODE REVIEW

File: chain/chain/src/chain.rs [hunk 1]
```diff
@@ -754,7 +754,9 @@ impl Chain {
         // the block might not have been what the block producer originally produced. Either way, it's
         // OK if we miss some cases here because this is just an optimization to avoid reprocessing
         // known invalid blocks so the network recovers faster in case of any issues.
-        if error.is_bad_data() && !matches!(error, Error::InvalidSignature) {
+        if error.is_bad_data()
+            && !matches!(error, Error::InvalidSignature | Error::InvalidBlockHeight(_))
```
Comment (shreyan-gupta) [inline chain/chain/src/chain.rs:758]: Minor point but just checking, in our sequence of checks that we do for block, how far down the list do we have `InvalidBlockHeight`? Because if it's quite up in the stack of validation checks, this can be a source of spam as we don't mark such blocks as invalid.

**Review by shreyan-gupta — APPROVED** [review]

File: chain/chain/src/chain.rs (hunk 1 above)
Comment (robin-near) [reply chain/chain/src/chain.rs:758]: It's pretty early. However, the is_bad_data() check here is not for the purpose of preventing spam. It's for the purpose of dealing with a class of bugs where we the network gets stuck and the recovery is slowed down by repeatedly processing invalid blocks. Invalid height is not quite relevant here because these invalid blocks are talking about recent blocks. But honestly, I can't say that I still have enough context to reason about this. It's possible that this isn't even relevant anymore due to stateless validation. Either way, logically it is incorrect to mark a block as invalid just because its height is too high due to where the receiving node currently is, so we should stop doing that anyway.
