### PR TITLE
bug: fix `network/routing.rs` tests

### LINKED ISSUE #5322: `routing::test_dropping_routing_messages` test is broken
```sh
cargo test --workspace --features test_features \
    --project integration-tests --test network \
    -- --exact routing::test_dropping_routing_messages
```

This hasn’t been caught because the test is guarded by a `cfg(feature = "test_features")` and since we don’t enable that feature on BuildKite the test has not been executed.

### PR DESCRIPTION
**Pull request by pmnoxx**
In `PeerActor` we have a logic which is used to drop duplicated messages if they happen within `50`ms. That constant used to be higher while the change was originally implemented.
```
/// Duplicated messages will be dropped if routed through the same peer multiple times.
pub const DROP_DUPLICATED_MESSAGES_PERIOD: Duration = Duration::from_millis(50);
```

In `network/routing.rs` tests we use structs `StateMachine` to test PR. The check coincidentally runs every `50ms`, which is sometimes too fast, sometimes too slow for the logic to drop duplicated messages to work.

The fix is to change constant inside testes from `50ms` to `1ms`.

Closes #5322

### CODE REVIEW

File: integration-tests/tests/network/runner.rs [hunk 1]
```diff
@@ -408,14 +412,19 @@ impl StateMachine {
...
+                                        debug!(target: "network", "{}: ping, pong check : {} {:?} {:?} expected {:?} {:?}",
+                                            num_prev_actions, source, pings, pongs, pings_expected, pongs_expected);
                                         if ping_ok && pong_ok {
                                             flag.store(true, Ordering::Relaxed);
                                         } else {
-                                            panic!(
-                                                "ping, pong check failed got: {:?} {:?}",
-                                                pings, pongs
-                                            );
+                                            if time.lock().unwrap().elapsed()
```
Comment (mina86) [inline integration-tests/tests/network/runner.rs:420]: I’d prefer `} else if {` to reduce amount of indentation.

**Review by mina86 — APPROVED** [review]

File: integration-tests/tests/network/runner.rs (hunk 1 above)
Comment (pmnoxx) [reply integration-tests/tests/network/runner.rs]: @mina86 I removed that else branch completely.
