### PR TITLE
fix: address inconsistencies in ColTransactionResult

### LINKED ISSUE #3478: Weird behaviour of ExecutionOutcome
**Describe the bug**
I’ve been running Indexer for testnet and got into weird situation.

Indexer was unable to handle ExecutionOutcome for receipt `6gGEKfo9eJ3KQvJcrork82QZ8RcZS9ZFs5rifwC9uej7`

Here’s the ExecutionOutcome

```
{
  "proof": [],
  "block_hash": "VBGfsfX538gamd9SH52M32Da8mTduwZTcqKCFuwMNkm",
  "id": "6gGEKfo9eJ3KQvJcrork82QZ8RcZS9ZFs5rifwC9uej7",
  "outcome": {
    "logs": [],
    "receipt_ids": [],
    "gas_burnt": 0,
    "tokens_burnt": "0",
    "executor_id": "eth2nearrelay10.testnet",
    "status": {
      "SuccessValue": ""
    }
  }
}
```

Pay attention to `block_hash`

RPC call for block by hash returns the information about the block at height `19165379`

RPC call for block by height returns `"DB Not Found Error: BLOCK HEIGHT: 19165379 \n Cause: Unknown"`

So the block with this height not included in chain. But somehow in the other block we’ve received the ExecutionOutcome with `block_hash` of not included block.

Is it expected behaviour or is it a bug? 

Let me know if I can add anything else to help investigate it.

**Expected behavior**
ExecutionOutcome `block_hash` can't be equal the block not included in chain

**Version (please complete the following information):**
- nearcore e76b8dd1f7aca44e348844303d290c3b9c9a4387 (built Indexer for Explorer on that commit)
- testnet

/cc @frol

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently we index execution outcome by transaction or receipt id, which means that if there is a fork, depending on the order we receive the blocks, we could overwrite the execution outcome on the canonical chain with the one on the fork. This causes problems for both indexer and rpc (see #3478). This PR fixes it by storing for each transaction hash or receipt id, a `Vec<ExecutionOutcomeWithIdAndProof>`, which includes execution outcome from every fork. When looking them up from rpc however, we always choose the result from the canonical chain. Fixes #3478.

Test plan
---------
* `test_fork_execution_outcome`
* nayduck
* test migration on testnet

### CODE REVIEW

File: neard/src/migrations.rs [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    let store = create_store(path);
+    if !near_config.client_config.archive {
+        // Non archival node. Perform a simply migration without necessarily fixing the inconsistencies
+        // since the old data will be garbage collected in five epochs
+        let mut store_update = store.store_update();
+        for (key, value) in store.iter_without_rc_logic(DBCol::ColTransactionResult) {
+            let outcome = ExecutionOutcomeWithIdAndProof::try_from_slice(&value).unwrap();
+            store_update.set_ser(DBCol::ColTransactionResult, &key, &vec![outcome]).unwrap();
+        }
+        store_update.commit().unwrap();
```
Comment (frol) [inline neard/src/migrations.rs:78]: Is it too expensive to fix all of those on non-archival nodes ("only" 5 epochs of data)? It would keep the migration simpler and don't introduce a corner case when the node gets migrated with this code path and then the user decides to restart the node as archival

**Review by frol — APPROVED** [review]

File: chain/chain/src/chain.rs [hunk 2]
```diff
@@ -2365,6 +2362,24 @@ impl Chain {
...
+    pub fn get_execution_outcome(
+        &mut self,
+        id: &CryptoHash,
+    ) -> Result<ExecutionOutcomeWithIdAndProof, Error> {
+        let outcomes = self.store.get_outcomes_by_id(id)?;
+        outcomes
+            .into_iter()
+            .find(|outcome| match self.get_block_header(&outcome.block_hash) {
+                Ok(header) => {
+                    let header = header.clone();
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply chain/chain/src/chain.rs:2376]: No it is not because of the mutable reference to self

File: neard/src/migrations.rs (hunk 1 above)
Comment (bowenwang1996) [reply neard/src/migrations.rs:78]: > Is it too expensive to fix all of those on non-archival nodes ("only" 5 epochs of data)? It would keep the migration simpler and don't introduce a corner case when the node gets migrated with this code path and then the user decides to restart the node as archival

It would make sense if we have properly separation between validator nodes and rpc nodes. As it stands today, validator nodes do not really care about this column and it doesn't make sense for them to do the migration.

File: chain/chain/src/chain.rs [hunk 3]
```diff
@@ -1829,31 +1829,30 @@ impl Chain {
...
-        let outcome = self.get_transaction_execution_result(hash)?;
+        let outcome: ExecutionOutcomeWithIdView = self.get_execution_outcome(id)?.into();
         let receipt_ids = outcome.outcome.receipt_ids.clone();
-        let mut transactions = vec![outcome];
-        for hash in &receipt_ids {
-            transactions
-                .extend(self.get_recursive_transaction_results(&hash.clone().into())?.into_iter());
+        let mut results = vec![outcome];
+        for receipt_id in &receipt_ids {
+            results.extend(self.get_recursive_transaction_results(receipt_id)?.into_iter());
```
Comment (evgenykuzyakov) [inline chain/chain/src/chain.rs:1845]:
```suggestion
            results.extend(self.get_recursive_transaction_results(receipt_id)?);
```

**Review by evgenykuzyakov — APPROVED** [review]

**Review by SkidanovAlex — APPROVED** [review]
