### PR TITLE
Log error for outdated node

### LINKED ISSUE #11928: feat(release) - log an error if the blockchain voted for version higher than the node's
During the binary release the protocol goes through a voting where it agrees to upgrade to the next protocol version in the next next epoch. For more details please see https://github.com/near/nearcore/blob/master/docs/practices/protocol_upgrade.md. 

Often times some nodes are not upgraded. Those nodes crash as soon as the protocol upgrade happens. This is undesired for multiple reasons:
* The blockchain loses some of its capacity.
* The validator will miss blocks and chunks, lose rewards and be kicked out, losing even more rewards. 
* The crashing nodes introduce noise during the sensitive period of protocol upgrade. 

The goal of this issue is to print an error message and/or otherwise signal to the node operator that the blockchain will upgrade to a version higher than the version supported by the node.

### PR DESCRIPTION
**Pull request by eagr**
closes #11928 

do we need testing for this? @wacban

### CODE REVIEW

File: chain/chain/src/chain.rs [hunk 1]
```diff
@@ -2218,6 +2219,17 @@ impl Chain {
...
+        let next_epoch_protocol_version =
+            self.epoch_manager.get_epoch_protocol_version(&next_epoch_id)?;
+        if next_epoch_protocol_version > PROTOCOL_VERSION {
+            error!(
+                "The client protocol version is about to be superseded, please upgrade nearcore as soon as possible. Client protocol version {}, new network protocol version {}",
+                PROTOCOL_VERSION,
+                next_epoch_protocol_version,
+            );
+        }
+
```
Comment (wacban) [inline chain/chain/src/chain.rs:2232]: nit1 - Can you move that to a helper method? This one is too long as is. 
nit2 - I typically prefer to perform checks in postprocess block - it just feels a bit safer knowing that the block is valid and processed.

**Review by wacban — COMMENTED** [review]
LGTM - just two small nits! 

re testing - I don't think there is any need for a unit test. It would be nice to test it manually at least once though. If you're down for it you can try the following: 
* get the current release neard (I think it should have version 72)
  * ./neard72 --version 
* start a small localnet
  * neard localnet -h
  * neard run (for each node)
* build neard from your PR - it should have version 73
  * ./neard73 --version
* upgrade all except one node
* see the error on that node that was not upgraded

File: chain/chain/src/chain.rs (hunk 1 above)
Comment (eagr) [reply chain/chain/src/chain.rs]: done

File: chain/chain/src/chain.rs [hunk 2]
```diff
@@ -2070,13 +2070,29 @@ impl Chain {
 
         self.check_orphans(me, *block.hash(), block_processing_artifacts, apply_chunks_done_sender);
 
+        self.check_if_upgrade_needed(&block_hash);
+
```
Comment (wacban) [inline chain/chain/src/chain.rs:2074]: ❤️

File: chain/chain/src/chain.rs [hunk 3]
```diff
@@ -2070,13 +2070,29 @@ impl Chain {
...
         // Determine the block status of this block (whether it is a side fork and updates the chain head)
         // Block status is needed in Client::on_block_accepted_with_optional_chunk_produce to
         // decide to how to update the tx pool.
         let block_status = self.determine_status(new_head, prev_head);
         Ok(AcceptedBlock { hash: *block.hash(), status: block_status, provenance })
     }
 
+    fn check_if_upgrade_needed(&self, block_hash: &CryptoHash) {
```
Comment (wacban) [inline chain/chain/src/chain.rs:2082]: I like that it doesn't return an error, it wouldn't make sense to stop processing a block if this check failed.

File: chain/chain/src/chain.rs [hunk 4]
```diff
@@ -2070,13 +2070,29 @@ impl Chain {
...
+            self.epoch_manager.get_next_epoch_protocol_version(block_hash)
+        {
+            if PROTOCOL_VERSION < next_epoch_protocol_version {
+                error!(
+                    "The protocol version is about to be superseded, please upgrade nearcore as soon as possible. Client protocol version {}, new protocol version {}",
+                    PROTOCOL_VERSION,
+                    next_epoch_protocol_version,
+                );
+            }
+        }
```
Comment (wacban) [inline chain/chain/src/chain.rs:2093]: mini nit - you can use the 
``` 
let Ok(x) = x else { return; };
```
pattern to return early and make the code less nested. Optional as this is more of a preference thing.

**Review by wacban — APPROVED** [review]
looks great, thanks!

File: chain/chain/src/chain.rs (hunk 3 above)
Comment (eagr) [reply chain/chain/src/chain.rs:2082]: yeah, that's exactly what I have in mind :)

File: chain/chain/src/chain.rs (hunk 4 above)
Comment (eagr) [reply chain/chain/src/chain.rs:2093]: If the logic is more complicated, I'd definitely do that.

**Comment by wacban** [comment]
jfyi part of our testing infra is broken, my naive attempt to fix it (restart it) didn't work, I will merge it once it's fixed

**Comment by eagr** [comment]
> (restart it)

worth a shot :)
