### PR TITLE
near-vm-runner: fix m1 build

### LINKED ISSUE #7580: Compile error on Mac M1
**Describe the bug**
`cargo check --tests --benches` fails on top of master on Mac M1 machines.

**To Reproduce**
```
$ cargo check --tests --benches
    Checking near-vm-runner v0.0.0 (/Users/akhi/projects/nearcore/runtime/near-vm-runner)
    Checking nearcore v0.0.0 (/Users/akhi/projects/nearcore/nearcore)
    Checking near-jsonrpc-tests v0.0.0 (/Users/akhi/projects/nearcore/chain/jsonrpc/jsonrpc-tests)
error[E0432]: unresolved import `crate::wasmer2_runner`
  --> runtime/near-vm-runner/src/tests/fuzzers.rs:15:12
   |
15 | use crate::wasmer2_runner::Wasmer2VM;
   |            ^^^^^^^^^^^^^^ could not find `wasmer2_runner` in the crate root

error[E0432]: unresolved import `wasmer_engine`
  --> runtime/near-vm-runner/src/tests/fuzzers.rs:11:5
   |
11 | use wasmer_engine::Executable;
   |     ^^^^^^^^^^^^^ use of undeclared crate or module `wasmer_engine`

    Checking near-jsonrpc-fuzz v0.0.0 (/Users/akhi/projects/nearcore/chain/jsonrpc/fuzz)
For more information about this error, try `rustc --explain E0432`.
error: could not compile `near-vm-runner` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Expected behavior**
`cargo check --tests --benches` should succeed.

**Version (please complete the following information):**
- nearcore commit/branch: `72affb9`
- rust version: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- local

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
Fixes #7580

### CODE REVIEW

File: runtime/near-vm-runner/src/tests/fuzzers.rs [hunk 1]
```diff
@@ -8,10 +8,12 @@ use near_primitives::version::PROTOCOL_VERSION;
 use near_vm_errors::{FunctionCallError, VMError};
 use near_vm_logic::mocks::mock_external::MockedExternal;
 use near_vm_logic::{VMConfig, VMContext};
+#[cfg(all(feature = "wasmer2_vm", target_arch = "x86_64"))]
 use wasmer_engine::Executable;
 
 use crate::internal::wasmparser::{Export, ExternalKind, Parser, Payload, TypeDef};
 use crate::internal::VMKind;
+#[cfg(all(feature = "wasmer2_vm", target_arch = "x86_64"))]
 use crate::wasmer2_runner::Wasmer2VM;
```
Comment (matklad) [inline runtime/near-vm-runner/src/tests/fuzzers.rs:17]: maybe move these imports into the function then?

**Review by matklad — APPROVED** [review]

File: runtime/near-vm-runner/src/tests/fuzzers.rs (hunk 1 above)
Comment (Ekleog-NEAR) [reply runtime/near-vm-runner/src/tests/fuzzers.rs]: Good idea, thanks :)
