### PR TITLE
fix(metrics): Use correct set of shards in validator metrics for chunk production and endorsements

### LINKED ISSUE #11950: Chunk endorsement by shard metrics must use shards chunks-endorsed, instead of shard chunks-produced
Currently the shard ids in the epoch validator info are the shards produced by the chunk producer. But the shards for which the node generates endorsements will be different and a larger set. We should update the metrics `near_validators_chunk_endorsements_produced_by_shard` and `near_validators_chunk_endorsements_expected_by_shard` to consider the shards for which chunks are endorsed instead of the shards for which the chunks are produced.

### PR DESCRIPTION
**Pull request by tayfunelmas**
Fixes #11950.

Change the `get_validator_info` function to use the correct set of shards for chunk endorsements. This function is used for the `validator_info` RPC and updating the prometheus metrics.

Today, there is `shards` field in `CurrentEpochValidatorInfo` that contains the set of shards the validator is supposed to produce chunks for (chunks-expected > 0). This field is used to update the prometheus metrics for block/chunk production stats as well as endorsement stats (ie. for each shard in this set, update the production and endorsement metrics).

However, the set of shards that a validator validates chunks is not equal to the shard it produces chunks for (the former is a larger set). As a result, we see less dimensions for endorsement metrics.

In this PR, we rename `shards` to `shards_produced` and add another field `shards_endorsed` in order to track these two different sets of shards. We also populate these fields by looking at the aggragator's chunk-stats (checking is expected > 0) instead of chunk-producer assignments.

Note that, this PR only fixes the input with `ValidatorInfoIdentifier::BlockHash` where the per-shard stats are available. `ValidatorInfoIdentifier::EpochId` is not fixed, since it does not have per-shard statistics.

Testing: Ran a mainnet RPC node with the changes and compared the result of "validator" RPC for the node and the mainnet canary RPC (without the changes).

### CODE REVIEW

File: chain/epoch-manager/src/lib.rs [hunk 1]
```diff
@@ -1503,26 +1504,26 @@ impl EpochManager {
             ValidatorInfoIdentifier::BlockHash(ref b) => self.get_epoch_id(b)?,
         };
         let cur_epoch_info = self.get_epoch_info(&epoch_id)?;
-        let cur_shard_layout = self.get_shard_layout(&epoch_id)?;
         let epoch_height = cur_epoch_info.epoch_height();
         let epoch_start_height = self.get_epoch_start_from_epoch_id(&epoch_id)?;
-        let mut validator_to_shard = (0..cur_epoch_info.validators_len())
```
Comment (tayfunelmas) [inline chain/epoch-manager/src/lib.rs:1509]: this block is moved to line 1515 because it is only needed for `ValidatorInfoIdentifier::EpochId` branch. The other branch uses the aggregator stats.

**Comment by Longarithm** [comment]
> his PR only fixes the input with ValidatorInfoIdentifier::BlockHash

You've meant the opposite (EpochId), right?

File: chain/epoch-manager/src/lib.rs [hunk 2]
```diff
@@ -1616,31 +1620,39 @@ impl EpochManager {
...
-                            .into_iter()
-                            .collect::<Vec<ShardId>>();
-                        shards.sort();
+                        // Collect the shards for which the validator was *expected* to produce at least one chunk.
+                        let mut shards_produced = chunks_stats_by_shard
+                            .iter()
+                            .filter_map(|(shard, stats)| (stats.expected() > 0).then_some(*shard))
+                            .collect_vec();
+                        shards_produced.sort();
+                        // Collect the shards for which the validator was *expected* to validate at least one chunk chunk.
```
Comment (Longarithm) [inline chain/epoch-manager/src/lib.rs:1629]:
```suggestion
                        // Collect the shards for which the validator was *expected* to validate at least one chunk.
```

Comment (Longarithm) [reply chain/epoch-manager/src/lib.rs:1629]: shards_endorsed will always be all shards, because even if chunk validator has one mandate, in 43200 blocks it will likely be randomly selected for each shard at least one. But I also don't see a reason to define validator info differently.

**Review by Longarithm — APPROVED** [review]
