### PR TITLE
fix(chain): validate chunk mask

### LINKED ISSUE #3586: Block::check_validity should check chunk mask
`Block::check_validity` only checks that the number of chunks included is correct, but doesn't check against chunk mask in `BlockHeaderV2`. This means that with multiple shards it's possible to manipulate `ShardChunkHeader::height_included` values in the block while still having it match the header.

### PR DESCRIPTION
**Pull request by mikhailOK**
Make header validation match chunk mask against chunks_included for V1
headers.
Make block validation match chunk mask in header against computed mask
from block body. Don't check chunks_included anymore, as it's checked
in header validation.
Also refactor chunks_included logic in Block::genesis as it was
unnecessarily complex and did not match the logic for non-genesis
blocks anyway.

Fixes #3586

Test plan
---------
Unit test

### CODE REVIEW

File: chain/chain/src/chain.rs [hunk 1]
```diff
@@ -3181,6 +3181,13 @@ impl<'a> ChainUpdate<'a> {
             return Err(ErrorKind::InvalidChunkMask.into());
         }
 
+        // Actually only needed for BlockHeaderV1
```
Comment (bowenwang1996) [inline chain/chain/src/chain.rs:3184]: why don't we do this only for `BlockHeaderV1` then

File: core/primitives/src/block_header.rs [hunk 2]
```diff
@@ -357,13 +357,14 @@ impl BlockHeader {
...
         chunk_tx_root: MerkleHash,
-        chunks_included: u64,
+        num_shards: u64,
         challenges_root: MerkleHash,
         timestamp: DateTime<Utc>,
         initial_gas_price: Balance,
         initial_total_supply: Balance,
         next_bp_hash: CryptoHash,
     ) -> Self {
+        let chunks_included = if height == 0 { num_shards } else { 0 };
```
Comment (bowenwang1996) [inline core/primitives/src/block_header.rs:367]: why does height matter here?

Comment (mikhailOK) [reply core/primitives/src/block_header.rs:367]: old code was `Block::compute_chunks_included(&chunks, 0)` with `0` instead of `height`

**Review by bowenwang1996 — APPROVED** [review]
