### PR TITLE
fix: make outcome ids ordered in storage

### LINKED ISSUE #3467: The order of ExecutionOutcomes
To properly implement accounts and access keys tracking (add, delete) in indexers we need to correct order of ExecutionOutcomes.

For example if in one block we have actions for the same `CreateAccount` and `DeleteAccount` we should create it and then delete it. But we have unordered outcomes so we might have try to delete account first and then create it what ends up in the wrong representation of the state in indexer.

How can we solve this?

/cc @frol @bowenwang1996 @mikhailOK @evgenykuzyakov

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently the outcome ids stored in `ColOutcomesByBlockHash` are not ordered, which causes problems for the indexer. This PR addresses this issue by making execution outcomes ordered within each shard and in storage it is keyed now by (block_hash, shard_id). Note that I have to make another migration because the 12->13 migration has already taken effect on testnet. Fixes #3467 

Test plan
---------
* nayduck
* migrate existing testnet data

### CODE REVIEW

File: core/store/src/migrations.rs [hunk 1]
```diff
@@ -320,3 +326,126 @@ pub fn migrate_13_to_14(path: &String) {
 
     set_store_version(&store, 14);
 }
+
+pub fn migrate_14_to_15(path: &String) {
```
Comment (evgenykuzyakov) [inline core/store/src/migrations.rs:330]: Would be great to add a comment here as well saying that it orders execution outcomes by replaying chunks.

**Review by evgenykuzyakov — APPROVED** [review]

File: chain/chain/src/store.rs [hunk 2]
```diff
@@ -2278,23 +2285,30 @@ impl<'a> ChainStoreUpdate<'a> {
...
-            outcomes_with_id.retain(|outcome| &outcome.block_hash != block_hash);
-            if outcomes_with_id.is_empty() {
-                self.gc_col(ColTransactionResult, &outcome_id.as_ref().into());
-            } else {
-                store_update.set_ser(
-                    ColTransactionResult,
-                    outcome_id.as_ref(),
-                    &outcomes_with_id,
-                )?;
+        for chunk_header in block.chunks().iter() {
```
Comment (frol) [inline chain/chain/src/store.rs:2291]:
```suggestion
        for chunk_header in &block.chunks() {
```

File: chain/chain/src/store.rs [hunk 3]
```diff
@@ -2278,23 +2285,30 @@ impl<'a> ChainStoreUpdate<'a> {
...
+            if chunk_header.height_included() == block.header().height() {
```
Comment (frol) [inline chain/chain/src/store.rs:2292]: It seems to be a common use-case now. Should we consider adding a new method on the Block like `included_chunks`?

File: chain/client/src/view_client.rs [hunk 4]
```diff
@@ -51,6 +51,7 @@ use crate::{
     GetStateChangesInBlock, GetValidatorInfo, GetValidatorOrdered,
 };
 use near_primitives::sharding::ShardChunk;
+use std::collections::HashMap;
```
Comment (frol) [inline chain/client/src/view_client.rs:54]: nit: could you move the last two `use`s to the relevant groups?

File: core/store/src/db.rs [hunk 5]
```diff
@@ -104,7 +104,7 @@ pub enum DBCol {
     ColBlockOrdinal = 40,
     /// GC Count for each column
     ColGCCount = 41,
-    /// GC helper column to get all Outcome ids by Block Hash
+    /// All Outcome ids by Block Hash. For each block it is ordered by execution order.
     ColOutcomesByBlockHash = 42,
```
Comment (frol) [inline core/store/src/db.rs:108]: I guess, we should reflect the change of the key type; it is no more the block hash alone, but also a shard id, right?

File: core/store/src/migrations.rs [hunk 6]
```diff
@@ -320,3 +326,126 @@ pub fn migrate_13_to_14(path: &String) {
...
+    let mut store_update = store.store_update();
+    let batch_size_limit = 10_000_000;
+    let mut batch_size = 0;
+
+    for (key, value) in store.iter_without_rc_logic(DBCol::ColOutcomesByBlockHash) {
+        let block_hash = CryptoHash::try_from_slice(&key).unwrap();
+        let block =
+            store.get_ser::<Block>(DBCol::ColBlock, &key).unwrap().expect("block should exist");
+
+        if block.chunks()[0].height_included() == block.header().height() {
```
Comment (frol) [inline core/store/src/migrations.rs:344]: It seems that you only migrate the first shard. Sharded networks (guildnet) will get into a broken state after this migration, right?

File: chain/indexer/src/streamer/streamer.rs [hunk 7]
```diff
@@ -283,23 +283,25 @@ async fn fetch_outcomes(
...
+                        e,
+                    );
+                    None
+                }
+            };
+            outcomes_with_receipts.insert(
+                outcome.id,
+                IndexerExecutionOutcomeWithReceipt { execution_outcome: outcome, receipt },
+            );
+        }
```
Comment (frol) [inline chain/indexer/src/streamer/streamer.rs:304]: @khorolets FYI, once this is landed to master, you may want to update the streamer implementation attaching the execution outcomes to the relevant chunks.

File: core/store/src/migrations.rs [hunk 8]
```diff
@@ -320,3 +326,126 @@ pub fn migrate_13_to_14(path: &String) {
...
+                .get_ser::<EpochInfo>(DBCol::ColEpochInfo, block.header().epoch_id().as_ref())
+                .unwrap()
+                .expect("epoch id should exist");
+            let protocol_version = epoch_info.protocol_version;
+
+            let mut new_execution_outcome_ids = vec![];
+            let mut local_receipt_ids = vec![];
+            let mut local_receipt_congestion = false;
+
+            // Step 0: execution outcomes of transactions
```
Comment (frol) [inline core/store/src/migrations.rs:362]: @khorolets FYI, this is probably the best resource to learn the order the execution inside a chunk is happening :smile:

File: chain/chain/src/store.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/chain/src/store.rs:2279]: this doesn't work because `chunks` returns `ChunksCollection` and the only way to turn it to an iterator is to call `.iter()` on it

File: chain/chain/src/store.rs (hunk 3 above)
Comment (bowenwang1996) [reply chain/chain/src/store.rs]: It is not easy without cloning due to how `ShardChunkHeader` works

**Review by frol — APPROVED** [review]

**Review by SkidanovAlex — APPROVED** [review]

**Comment by frol** [comment]
@bowenwang1996 Why the RPC query test was removed in this PR?

**Comment by bowenwang1996** [comment]
> @bowenwang1996 Why the RPC query test was removed in this PR?

Because it messes with the execution outcomes stored in storage. We plan to remove rpc routing anyways and that test relies on having rpc routing.

**Review by frol — APPROVED** [review]
Sounds good to me
