### PR TITLE
fix: properly handle genesis as part of stateless validation

### LINKED ISSUE #10502: [stateless_validation] Handle production of state witness for first chunk after genesis
@Longarithm has more context on this problem.

We are currently unable to handle production of the state witness for the first chunk after genesis as it's not possible to run the genesis chunk in runtime. For now we have just hacked up a solution to send an empty state witness and the validators can ignore this and directly send the endorsement.

Note: This is only a problem for starting a new blockchain, and does not affect mainnet, nevertheless should be properly addressed.

### PR DESCRIPTION
**Pull request by pugachAG**
This PR removes "approve anything" shortcut when previous chunk is part of genesis. The only difference in case of genesis is that we don't want to execute main state transition and instead just check that post state root matches genesis state root for that shard.

This also exposed some issue I had to fix to make tests work:
* `MockEpochManager::get_epoch_chunk_producers` returns empty Vec which results in `Chain:: should_produce_state_witness_for_this_or_next_epoch` returning `false`. Fixed by adding `is_chunk_producer_for_epoch` as part of `EpochManagerAdapter` so `MockEpochManager` can override it.
* `test_chunk_state_witness_bad_shard_id` test started failing: this actually uncovered a real issue which could result in crashing chunk validator when state witness contains invalid shard id, fixed in c5b2c5e1ea5bf470ceb26fb9681d293765bf5362

Closes #10502.

### CODE REVIEW

**Comment by Longarithm** [comment]
@staffik @jancionear could you review please? If you LGTM it then I'll stamp an approval as well.

**Comment by staffik** [comment]
@pugachAG please let me know when I should proceed with review, I see quite of lot changes keep being added now.

**Comment by pugachAG** [comment]
@staffik @jancionear this PR is ready for review now

File: integration-tests/src/tests/client/features/adversarial_behaviors.rs [hunk 1]
```diff
@@ -264,12 +264,8 @@ fn test_banning_chunk_producer_when_seeing_invalid_chunk_base(
...
                             // With stateless validation the block usually isn't skipped. Chunk validators
                             // won't send chunk endorsements for this chunk, which means that it won't be
-                            // included in the block at all. The only exception is the first few blocks after
-                            // genesis, which are currently handled in a special way.
-                            // In this test the block with height 2 is skipped.
-                            // TODO(#10502): Properly handle blocks right after genesis, ideally no blocks
-                            // would be skipped when using stateless validation.
-                            this_block_should_be_skipped = height < 3;
+                            // included in the block at all.
+                            this_block_should_be_skipped = false;
```
Comment (staffik) [inline integration-tests/src/tests/client/features/adversarial_behaviors.rs:268]: In case `uses_stateless_validation` it looks like we do not even need to run the containing loop.
What about `if height > 1 && !uses_stateless_validation {` and move the comment above?

**Review by staffik — APPROVED** [review]
LGTM

File: integration-tests/src/tests/client/features/adversarial_behaviors.rs (hunk 1 above)
Comment (pugachAG) [reply integration-tests/src/tests/client/features/adversarial_behaviors.rs]: It doesn't look like we can skip the loop since it also updates `invalid_chunks_in_this_block` which is used later.
I've updated this to avoid setting `this_block_should_be_skipped = false` here since it is noop: 10a99ffc28deabba8b398c11de18fc7e76a9e308

File: core/primitives/src/block_header.rs [hunk 2]
```diff
@@ -745,6 +745,11 @@ impl BlockHeader {
         }
     }
 
+    #[inline]
+    pub fn is_genesis(&self) -> bool {
+        self.prev_hash() == &CryptoHash::default()
+    }
+
```
Comment (jancionear) [inline core/primitives/src/block_header.rs:752]: Nice, I was really missing a function like this.

File: chain/client/src/stateless_validation/chunk_validator.rs [hunk 3]
```diff
@@ -341,6 +352,10 @@ fn validate_source_receipt_proofs(
     // Iterate over blocks between last_chunk_block (inclusive) and last_last_chunk_block (exclusive),
     // from the newest blocks to the oldest.
     for block in receipt_source_blocks {
+        if block.header().is_genesis() {
+            assert_eq!(receipt_source_blocks.len(), 1);
+            break;
+        }
```
[the remark this answers is not in the document]
Comment (jancionear) [reply chain/client/src/stateless_validation/chunk_validator.rs:358]: nit: Maybe it would be nicer to have an explicit condition: `if witnes for genesis { source receipts should be empty}`. I feel that it would be easier to reason about than the current solution.

File: chain/client/src/view_client.rs [hunk 4]
```diff
@@ -280,7 +280,7 @@ impl ViewClientActor {
             let cps: Vec<AccountId> = shard_ids
                 .iter()
                 .map(|&shard_id| {
-                    let cp = epoch_info.sample_chunk_producer(block_height, shard_id);
```
Comment (jancionear) [inline chain/client/src/view_client.rs:283]: Is it safe to `unwrap()` here? The function returns an Error, so maybe it would be better to return an error.
(Also applies to other `unwraps()` on the new `sample_chunk_producer`)

File: core/primitives/src/epoch_manager.rs [hunk 5]
```diff
@@ -1081,33 +1081,37 @@ pub mod epoch_info {
...
                     let seed =
                         Self::chunk_produce_seed(protocol_version, &v4.rng_seed, height, shard_id);
                     let shard_id = shard_id as usize;
-                    let sample = v4.chunk_producers_sampler[shard_id].sample(seed);
-                    v4.chunk_producers_settlement[shard_id][sample]
+                    let sample = v4.chunk_producers_sampler.get(shard_id)?.sample(seed);
+                    v4.chunk_producers_settlement.get(shard_id)?.get(sample).copied()
                 }
             }
         }
```
Comment (jancionear) [inline core/primitives/src/epoch_manager.rs:1117]: > test_chunk_state_witness_bad_shard_id test started failing: this actually uncovered a real issue which could result in crashing chunk validator when state witness contains invalid shard id, fixed in https://github.com/near/nearcore/commit/c5b2c5e1ea5bf470ceb26fb9681d293765bf5362

So IIUC we are now validating the `shard_id` of `ChunkStateWitness` by trying to sample a chunk producer for this `shard_id`. That feels a bit hacky, maybe we should have some function that prevalidates the witness header (or just shard_id) before doing anything else. Sampling the producer could potentially work with invalid shard ids (e.g `producers[(height + shard) % producers.len()`), so it's not obvious that it can be done with untrusted data.

Comment (jancionear) [reply core/primitives/src/epoch_manager.rs:1117]: It's another time that an invalid shard_id could cause a crash (https://github.com/near/nearcore/pull/10621 ...), I think it would be good to go through the code and just remove all usages of `[shard_id]`. It causes problems now, and it's gonna be even worse with resharding :/ I'll make an issue.

**Review by jancionear — COMMENTED** [review]
Looks nice, left some comments

File: core/primitives/src/epoch_manager.rs (hunk 5 above)
Comment (jancionear) [reply core/primitives/src/epoch_manager.rs:1117]: Opened https://github.com/near/nearcore/issues/10648

File: chain/epoch-manager/src/adapter.rs [hunk 6]
```diff
@@ -292,6 +292,18 @@ pub trait EpochManagerAdapter: Send + Sync {
         )))
     }
 
+    /// This function is only needed to have a 'return true' implementation
+    /// as part of MockEpochManager to make tests work with stateless validation
+    /// enabled.
+    /// TODO(#10640): remove this after we get rid of MockEpochManager
+    fn is_chunk_producer_for_epoch(
```
[the remark this answers is not in the document]
Comment (pugachAG) [reply chain/epoch-manager/src/adapter.rs:299]: Yeah, I see how it can be confusing. What I meant here is that it doesn't have to be a part of `EpochManagerAdapter` trait. I guess it is not that important, so I will just drop the comment and close the issue.

File: chain/client/src/client.rs [hunk 7]
```diff
@@ -960,6 +956,9 @@ impl Client {
                     prev_block_hash,
                 ),
             ));
+            if txs.storage_proof.is_none() {
+                txs.storage_proof = Some(Default::default());
+            }
```
[the remark this answers is not in the document]
Comment (pugachAG) [reply chain/client/src/client.rs:961]: We have the following check as part of `create_state_witness_inner`:
```
        let new_transactions_validation_state = if new_transactions.is_empty() {
            PartialState::default()
        } else {
            // With stateless validation chunk producer uses recording reads when validating transactions. The storage proof must be available here.
            transactions_storage_proof.expect("Missing storage proof for transactions validation")
        };
  ```
  so we need to have some storage proof just  so we can produce state witness

File: chain/client/src/stateless_validation/chunk_validator.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (pugachAG) [reply chain/client/src/stateless_validation/chunk_validator.rs:358]: This assert is not part of validation logic, it ensures that our chain is in the valid state (`receipt_source_blocks` is not calculated using our own chain state, not state witness). I will replace it with proper error handling so you feel better about it 😉 

> Maybe it would be nicer to have an explicit condition

It is a bit more code, but indeed should be easier to understand, done

**Review by Longarithm — APPROVED** [review]
Approving to unblock

**Review by jancionear — APPROVED** [review]
