### PR TITLE
fix(runtime): add cache identifier label to compiled contract cache metrics

### LINKED ISSUE #15317: AnyCache metrics singleton assumption
### Description

`AnyCache` metrics are reported assuming only single instance of the cache exists, which is a very fragile assumption, not enforced in any way.
See https://github.com/near/nearcore-private/pull/194#discussion_r2877935463 for more context.

### PR DESCRIPTION
**Pull request by pugachAG**
- Remove singleton assumption from AnyCache metrics by adding an optional identifier field
- Metrics are only reported when the identifier is set, and it is used as a `cache_id` label on the `IntGaugeVec`
- The identifier is set to `filesystem_{contract_cache_path}` in `with_memory_cache`
- Closes #15317

### CODE REVIEW

**Comment by pugachAG** [comment]
@jancionear addressed in 1cc7ac692

File: runtime/near-vm-runner/src/metrics.rs [hunk 1]
```diff
@@ -33,18 +33,20 @@ static COMPILED_CONTRACT_CACHE_LOOKUPS_TOTAL: LazyLock<IntCounterVec> = LazyLock
     .unwrap()
 });
 
-static COMPILED_CONTRACT_CACHE_ITEMS: LazyLock<IntGauge> = LazyLock::new(|| {
-    try_create_int_gauge(
+static COMPILED_CONTRACT_CACHE_ITEMS: LazyLock<IntGaugeVec> = LazyLock::new(|| {
+    try_create_int_gauge_vec(
         "near_vm_compiled_contract_cache_items",
```
Comment (jancionear) [inline runtime/near-vm-runner/src/metrics.rs]: nit: metric name refers to compile contract cache, even though it could be a different kind of cache. Something like `near_any_cache_items` would be more generic.

File: runtime/near-vm-runner/src/cache.rs [hunk 2]
```diff
@@ -309,13 +310,26 @@ impl FilesystemContractRuntimeCache {
...
+        let any_cache = if let Some(id) = memcache_metrics_identifier {
+            any_cache.with_metrics_identifier(id)
+        } else {
+            any_cache
+        };
+        #[cfg(not(feature = "metrics"))]
+        assert!(
+            memcache_metrics_identifier.is_none(),
+            "memcache_metrics_identifier is only supported with the `metrics` feature"
+        );
```
Comment (jancionear) [inline runtime/near-vm-runner/src/cache.rs:325]: nit: I'd just silently ignore the metric name when metrics are not enabled

File: runtime/near-vm-runner/src/cache.rs [hunk 3]
```diff
@@ -253,7 +253,7 @@ impl FilesystemContractRuntimeCache {
         StorePath: AsRef<std::path::Path> + ?Sized,
         ContractCachePath: AsRef<std::path::Path> + ?Sized,
     {
-        Self::with_memory_cache(home_dir, store_path, contract_cache_path, 0)
+        Self::with_memory_cache(home_dir, store_path, contract_cache_path, 0, None)
```
Comment (jancionear) [inline runtime/near-vm-runner/src/cache.rs:254]: Why `None` here? it creates an `AnyCache`.

File: runtime/near-vm-runner/src/metrics.rs (hunk 1 above)
Comment (pugachAG) [reply runtime/near-vm-runner/src/metrics.rs]: good point, done in 9b2e58687

File: runtime/near-vm-runner/src/cache.rs (hunk 2 above)
Comment (pugachAG) [reply runtime/near-vm-runner/src/cache.rs:325]: downgraded to debug_assert to serve as documentation 2377f23d9

File: runtime/near-vm-runner/src/cache.rs (hunk 3 above)
Comment (pugachAG) [reply runtime/near-vm-runner/src/cache.rs:254]: `memcache_expected_item_count` is set to `0`, so having metric identifier is kind of pointless here
