### PR TITLE
fix: block apply in the past 

### LINKED ISSUE #8741: Support block replayability with enabled flat storage
With flat storage enabled, we currently don't support state-viewer apply range command. See original discussions [here](https://github.com/near/nearcore/pull/8697#discussion_r1132607373) and [here](https://near.zulipchat.com/#narrow/stream/297873-pagoda.2Fnode/topic/replayability.20and.20flat.20storage/near/342096518).

So far we know that:
* it is annoying to some developers, as this command is useful for them for replaying blocks and get proxies for performance estimation;
* replaying blocks is an actual usecase by some NEAR users, though there was no critical demand for it so far.

So this is considered lower priority than #7327. However, let's provide several options to solve it.

### Recreate FS

Just create FS from scratch, using trie. @mm-near confirmed once that it takes < 1h on rpc nodes.

#### Concerns
* If shard size is too big, FS creation time grows with it.
* Waiting for 1h to replay a single block is annoying.

### Recreate "partial" FS

Some kind of hack: store all trie keys ever read for each specific block; if we need to replay a block, create "partial" FS including only these keys and execute a block, no issue should occur.

#### Concerns
* We don't store these "trie keys ever read" now. If we have some range in history for which they are not stored, it is not clear how to create this "snapshot".
* Increase of disk usage

### Fallback to Trie

Fallback to Trie makes a lot of sense; however, it would spoil chunk cache. But it can be solved if we specifically disable chunk cache during storage_read, and other storage ops when we use FS there as well.

#### Concerns
* Design of chunk cache will be even more hacky. It is already annoying to enable/disable chunk cache before/after funcall execution.

### FS rollback

If block to replay is not far away, we can rollback flat storage, until its head is the same as desired block.

#### Concerns
* We don't support rollback yet. Storing "old" values in deltas is technically annoying but can be done in, say, 2-3 weeks.
* If block is too far away (years ago?), rollback takes a lot of time.

### PR DESCRIPTION
**Pull request by Trisfald**
This PR fixes commands such as `neard view-state apply` and `neard view-state apply-range` when used on a block height that doesn't have flat storage built for it. 

It works by re enabling the feature of accessing trie nodes without paying gas costs (removed in #10490).

Probably it also fixes #8741.

### CODE REVIEW

File: chain/chain/src/runtime/mod.rs [hunk 1]
```diff
@@ -745,6 +745,13 @@ impl RuntimeAdapter for NightshadeRuntime {
             StorageDataSource::Db => {
                 self.tries.get_trie_for_shard(shard_uid, storage_config.state_root)
             }
+            StorageDataSource::DbTrieOnly => {
+                // If there is no flat storage on disk, use trie but simulate costs with enabled
+                // flat storage by not charging gas for trie nodes.
```
Comment (wacban) [inline chain/chain/src/runtime/mod.rs:750]: Can you add that this should not be used in production please?

File: tools/state-viewer/src/apply_chain_range.rs [hunk 2]
```diff
@@ -126,6 +126,7 @@ fn apply_block_from_range(
     csv_file_mutex: &Mutex<Option<&mut File>>,
     only_contracts: bool,
     use_flat_storage: bool,
+    use_trie_for_free: bool,
```
Comment (wacban) [inline tools/state-viewer/src/apply_chain_range.rs:129]: While technically accurate this name doesn't quite convey the message for me :) How about something like `use_flat_storage_from_trie` or similar?

File: tools/state-viewer/src/apply_chain_range.rs [hunk 3]
```diff
@@ -232,9 +233,16 @@ fn apply_block_from_range(
                 return;
             }
         }
+
+        let mut storage =
+            RuntimeStorageConfig::new(*chunk_inner.prev_state_root(), use_flat_storage);
+        if use_trie_for_free {
+            storage.source = StorageDataSource::DbTrieOnly;
+        }
```
Comment (wacban) [inline tools/state-viewer/src/apply_chain_range.rs:241]: It seems like use flat storage and source should be exclusive options. Can you structure it that way in code?

File: tools/state-viewer/src/cli.rs [hunk 4]
```diff
@@ -212,27 +217,35 @@ pub struct ApplyChunkCmd {
...
+        .unwrap()
     }
 }
 
 #[derive(clap::Parser, Copy, Clone, Debug, Eq, PartialEq)]
 pub enum ApplyRangeMode {
     /// Applies chunks one after another in order of increasing heights.
-    /// TODO(#8741): doesn't work. Remove dependency on flat storage
-    /// by simulating correct costs. Consider reintroducing DbTrieOnly
-    /// read mode removed at #10490.
```
Comment (wacban) [inline tools/state-viewer/src/cli.rs:230]: nice!

File: tools/state-viewer/src/cli.rs [hunk 5]
```diff
@@ -257,6 +270,10 @@ pub struct ApplyRangeCmd {
     only_contracts: bool,
     #[clap(long)]
     use_flat_storage: bool,
+    /// Use the data stored in trie, but without paying extra gas costs.
+    /// This could be used to simulate flat storage when the latter is not present.
+    #[clap(long)]
+    use_trie_for_free: bool,
```
Comment (wacban) [inline tools/state-viewer/src/cli.rs:276]: This is just fine as is but I wonder if we could auto detect the right configuration. It should be possible to check
a) if flat storage should be used, based on the protocol version of the block
b) if flat storage is present at the given height

Then you can setup the db source based on that. This is totally optional as in practice we will almost always use (false, true).

File: tools/state-viewer/src/commands.rs [hunk 6]
```diff
@@ -739,9 +771,11 @@ pub(crate) fn replay_chain(
     }
 }
 
-pub(crate) fn resulting_chunk_extra(result: &ApplyChunkResult, gas_limit: Gas) -> ChunkExtra {
-    // TODO(congestion_control): is it okay to use latest protocol version here for the chunk extra?
-    let protocol_version = PROTOCOL_VERSION;
+pub(crate) fn resulting_chunk_extra(
+    result: &ApplyChunkResult,
+    gas_limit: Gas,
+    protocol_version: ProtocolVersion,
```
Comment (wacban) [inline tools/state-viewer/src/commands.rs:777]: Nice!

File: tools/state-viewer/src/commands.rs [hunk 7]
```diff
@@ -207,8 +223,14 @@ pub(crate) fn apply_chunk(
         target_height,
         None,
         use_flat_storage,
+        use_trie_for_free,
     )?;
-    println!("resulting chunk extra:\n{:?}", resulting_chunk_extra(&apply_result, gas_limit));
+    // Most probably `PROTOCOL_VERSION` won't work if the target_height points to a time
+    // before congestion control has been introduced.
```
Comment (wacban) [inline tools/state-viewer/src/commands.rs:229]: Can you add a `TODO(congestion_control) Get the correct protocol version` here? Or just do it, I think you have all the data you need in place to get the version and pass it in.

**Review by wacban — COMMENTED** [review]
Looks great I just have some nice and minor comments!

File: tools/state-viewer/src/apply_chain_range.rs (hunk 2 above)
Comment (Trisfald) [reply tools/state-viewer/src/apply_chain_range.rs:129]: Yeah I didn't like the name
I will go for `use_flat_storage_from_trie` if there aren't any better suggestions!

File: tools/state-viewer/src/apply_chain_range.rs (hunk 3 above)
Comment (Trisfald) [reply tools/state-viewer/src/apply_chain_range.rs:241]: I have started in such a way, but then I realized you could potentially use both together.. for example use flat storage and still access trie for free. 
No strong opinion if you prefer I'll make the options in CLI exclusive

File: tools/state-viewer/src/cli.rs (hunk 5 above)
Comment (Trisfald) [reply tools/state-viewer/src/cli.rs:276]: Interesting idea, maybe for improvement as a default it could use autodetect, I'll file an issue. I feel there are interesting scenarios (to check some stuff) where someone would prefer to fine tune the flags, so it makes sense to leave such option available

File: tools/state-viewer/src/commands.rs (hunk 7 above)
Comment (Trisfald) [reply tools/state-viewer/src/commands.rs:229]: I'll try to get the data and fallback into a TODO if a fail hard 🙃

File: tools/state-viewer/src/apply_chain_range.rs (hunk 3 above)
Comment (wacban) [reply tools/state-viewer/src/apply_chain_range.rs:241]: When would it be possible to use both?

Comment (wacban) [reply tools/state-viewer/src/apply_chain_range.rs:241]: I think when flat storage is enabled we don't read trie at all (except for the non-inlined values).

File: tools/state-viewer/src/cli.rs (hunk 5 above)
Comment (wacban) [reply tools/state-viewer/src/cli.rs:276]: Yeah in the follow up you could have something like `enum StorageSource { AutoDetect, Trie, TrieFree, FS }`

File: tools/state-viewer/src/apply_chain_range.rs (hunk 3 above)
Comment (Trisfald) [reply tools/state-viewer/src/apply_chain_range.rs:241]: I'm referring to this struct

```
pub struct RuntimeStorageConfig {
    pub state_root: StateRoot,
    pub use_flat_storage: bool,
    pub source: StorageDataSource,
    pub state_patch: SandboxStatePatch,
}
```

API-wise it gives the impression `use-flat-storage` is orthogonal from the `StorageDataSource`. You can use flat storage or not over a DB that charges gas costs or not. 
Yes not charging gas costs is similar to using flat-storage in some contexts (replaying block)

Comment (wacban) [reply tools/state-viewer/src/apply_chain_range.rs:241]: Ah well then this struct is wrong too :) Given the source is already there the 'use_flat_storage' should be derivable from it. I would just remove it. If you don't want to go so far in this PR perhaps you can just add a new ctor? I just dislike this pattern of calling ctor and then immediately overwriting one of the fields, it seems very volatile.

Comment (Trisfald) [reply tools/state-viewer/src/apply_chain_range.rs:241]: Agree, I'll add another constructor!

Comment (Trisfald) [reply tools/state-viewer/src/apply_chain_range.rs]: I have made some sweeping changes to make stuff more explicit. No more flags to enable flat storage or free tries, instead now there's an enum `StorageSource` with all different options

File: chain/chain/src/types.rs [hunk 8]
```diff
@@ -282,6 +287,19 @@ impl RuntimeStorageConfig {
             state_patch: Default::default(),
         }
     }
+
+    /// Creates a [RuntimeStorageConfig] with [StorageDataSource::DbTrieOnly].
+    /// Flat storage is disabled because it is implied to be missing.
+    ///
+    /// This's meant to be used only to replay blocks.
+    pub fn with_db_trie_only(state_root: StateRoot) -> Self {
```
Comment (wacban) [inline chain/chain/src/types.rs:295]: nit: `new_with_db_trie_only`

**Review by wacban — APPROVED** [review]
LGTM!
