### PR TITLE
fix: default genesis minimum gas price

### LINKED ISSUE #7466: Inconsistent min_gas_price value when in localnet/sandbox
**Describe the bug**
On localnet or a sandbox node, gas estimations are 10x the amount. Seems this happening since `min_gas_price` is set to `1_000_000_000` instead of `100_000_000` which is what is found on mainnet/testnet. From my findings, `BlockEconomicsConfig::min_gas_price` determines the min_gas_price dynamically and lowers the min_gas_price to `100_000_000` for mainnet/testnet since their genesis protocol version is below a threshold. Meanwhile newly launched localnet or sandbox nodes have protocol version of 56 as of the time of writing this issue which doesn't meet the threshold and causes this inconsistency.

**To Reproduce**
- clone `https://github.com/near/workspaces-rs/`
- checkout branch `phuong/test/proxy`
- run `cargo run --example proxy` and then an error should occur like the following:
```
Error: handler error: [An error happened during transaction execution: InvalidAccessKeyError(NotEnoughAllowance { account_id: AccountId("dev-20220823224325-18831006822820"), public_key: ed25519:FzLCgiBnbhUvmcX78YWdugM7oapurcXcjAS4Fwt3hXi7, allowance: 56287890191155200000000, cost: 187424484981165931516950 })]
```
- to test for newer changes once changes are made to nearcore:
  - `cd nearcore`
  - `make sandbox`
  - `cd workspaces-rs`
  - `NEAR_SANDBOX_BIN_PATH=/abolute/path/to/nearcore/sandbox/debug/neard cargo run --example proxy` where the error no longer occurs

**Version (please complete the following information):**
- nearcore master
- local

**Additional context**
Initial conversation on it in zulip:
https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/Inconsistent.20min_gas_price.20on.20localnet.2Fsandbox/near/294942074

### PR DESCRIPTION
**Pull request by jakmeier**
Update the default value for `min_gas_price` when creating a new chain
to the effective value we use in mainnet today. (10e9 ->10e8)

This changes the gas price for new chains, localnet and sandbox.

Also add some comments to `fn min_gas_price` to improve clarity.

Resolves #7466

### CODE REVIEW

File: nearcore/src/config.rs [hunk 1]
```diff
@@ -107,8 +107,8 @@ pub const NUM_BLOCKS_PER_YEAR: u64 = 365 * 24 * 60 * 60;
 /// Initial gas limit.
 pub const INITIAL_GAS_LIMIT: Gas = 1_000_000_000_000_000;
 
-/// Initial gas price.
-pub const MIN_GAS_PRICE: Balance = 1_000_000_000;
+/// Initial and minimum gas price.
```
Comment (matklad) [inline nearcore/src/config.rs:110]: Could you expand this a bit? I want to capture that this is *default* initial price -- what we use in tests and sandbox. The actual price is whatever is in config of a particular chain. Maybe even rename it to `DEFAULT_MIN_GAS_PRICE`?

**Comment by matklad** [comment]
@mm-near could you take a look here or assign a better reviewer? What happens here makes sense to me, but I must confess I don't know much about our gas pricing stuff yet.

File: nearcore/src/config.rs (hunk 1 above)
Comment (jakmeier) [reply nearcore/src/config.rs:110]: That was exactly my thought process as well. I already changed the name to exactly your suggestion and wrote a comment. But then I realised that this is true for all the constants in this file that relate to genesis. They are all used as default values when generating a new genesis file. So it felt a bit out of place to add specific comments to this particular constant. So I removed my comment and thought it might be better to leave it as it is.

Clearly this is somewhat confusing still. But I don't know where best to add this information. Prefixing all the constants with `DEFAULT_` seems a bit verbose. Adding a comment to each constant also seems verbose. But do you think it would be worth it?

Comment (matklad) [reply nearcore/src/config.rs:110]: :thinking: I think we might want to do an overhaul of `GenesisConfig`. We have too many defaults there: 

* SmartDefault
* serde defaults
* these constants

I think ideally we'd do a manual `impl Default` which just sets all of the constants, and then adjust everything else to build on that, but this is out of scope for the PR

Comment (mm-near) [reply nearcore/src/config.rs:110]: Yeah - we should redesign how we're handing genesis configs. As currently we roughly need to cover 3 scenarios:

* mainnet/testnet - where we can no longer change the 'original' file
* sandbox - where we can setup whatever we want - but it should match mainnet/testnet behavior
* localnet/shardnet etc - where can setup whatever we want - and doesnt' have to match mainnet/testnet behavior.

We have a lot of code to handle the case number 1  (the code with MIN_GAS_PRICE_NEP_92_FIX is a great example of this).

I'd actually suggest, that for case 1) - we do something similar to what we do for gas pricing. By having a 'view' of the genesis_$PROTOCOL_VERSION_mainnet.json and genesis_$PROTOCOL_VERSION_testnet.json somewhere in the code..

But that's outside of this PR scope.

**Review by mm-near — APPROVED** [review]
