### PR TITLE
fix: flaky prefetcher tests

### LINKED ISSUE #8252: Storage prefetch tests are flaky
For more context see the [discussion in zulip](https://near.zulipchat.com/#narrow/stream/295302-general/topic/test_basic_prefetch_account.20fails)

Recent changes that might affect this test:
* https://github.com/near/nearcore/pull/8205
* https://github.com/near/nearcore/pull/8207

Some failures instances
* [test_basic_prefetch_account](https://buildkite.com/nearprotocol/nearcore/builds/23421#01852fc5-d3b6-4b70-9de0-5ee6e082b419)
* [test_prefetch_multiple_accounts](https://buildkite.com/nearprotocol/nearcore/builds/23406#01852ed1-f2ab-40ca-8e59-b811c1429793)
* [another test_basic_prefetch_account](https://buildkite.com/nearprotocol/nearcore/builds/23424#01852fe4-e82a-4071-b496-a1384731e592)

### PR DESCRIPTION
**Pull request by jakmeier**
Prefetcher tests have become flaky in CI lately, failing with
`"unexpected number of prefetched values"`.

I was not able to reproduce it locally. But there is a timeout that
is at least one source for flakyness. This commit removes this
source by properly waiting on the background threads to finish
instead of relying on a timeout.

Hopefully resolves  #8252. (Will have to reopen if not.)

### CODE REVIEW

File: runtime/runtime/src/prefetch.rs [hunk 1]
```diff
@@ -346,8 +346,35 @@ mod tests {
...
+                dropped.store(true, std::sync::atomic::Ordering::Release);
+            });
+            let spawned = Instant::now();
+            while !dropped.load(std::sync::atomic::Ordering::Acquire) {
+                std::thread::yield_now();
+                // 100ms should be enough to finish pending requests. If not,
+                // we should check how the prefetcher affects performance.
+                assert!(
+                    spawned.elapsed() < Duration::from_millis(100),
+                    "timeout while waiting for background threads to terminate"
```
Comment (pugachAG) [inline runtime/runtime/src/prefetch.rs:374]: What do you think about removing explicit timeout handling from the test code and let the test runner handle it? With #8207 we have proper per-test time limit, so we not longer have obscure CI failures in case of timeouts.

**Review by pugachAG — APPROVED** [review]

File: runtime/runtime/src/prefetch.rs (hunk 1 above)
Comment (pugachAG) [reply runtime/runtime/src/prefetch.rs:374]: Got it, makes sense!

File: runtime/runtime/src/prefetch.rs [hunk 2]
```diff
@@ -346,8 +346,35 @@ mod tests {
...
+        // Looking at `Pending` slots in the prefetching area is not sufficient
+        // here because threads can be in `Trie::lookup` between nodes, at which
+        // point no slot is reserved for them but they are still doing work.
+        //
+        // Solution: drop `tries`, which also drops prefetchers. In particular,
+        // we want to drop the `PrefetchingThreadsHandle` stored in tries. This
+        // causes all background threads to stop after they finish the current
+        // work. It will even join them and wait until all threads are done.
+        //
+        // Because threads are joined, there is also a possibility this will
```
Comment (akhi3030) [inline runtime/runtime/src/prefetch.rs:359]: nit: is it worth clarifying what `this` refers to here?  Maybe replace it with `drop(tries)`?

**Comment by jakmeier** [comment]
This needs a code owner approval before I can merge it. @Longarithm or @akhi3030 maybe?

**Review by akhi3030 — APPROVED** [review]
