### PR TITLE
fix(jsonrpc): Fix metrics usage and signature to prevent fails

### LINKED ISSUE #4063: state_sync.py: Unreachable error occurred
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/104936
```
[2mMar 09 17:12:50.914[0m [34mDEBUG[0m chain: Verifying challenges []    
[2mMar 09 17:12:50.914[0m [33m WARN[0m jsonrpc: Unreachable error occurred: DB Not Found Error: CHUNK EXTRA: 8veiAXzFM9bBvFotemJDzpcUzj3gRPmuN1y2WipvQJ4s:0 
 Cause: Unknown
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: InconsistentCardinality { expect: 1, got: 2 }', /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.11.0/src/vec.rs:258:49
stack backtrace:
[2mMar 09 17:12:50.914[0m [34mDEBUG[0m chain: Catching up: removing prev=`8veiAXzFM9bBvFotemJDzpcUzj3gRPmuN1y2WipvQJ4s` from the queue. I'm Some("test0")    
[2mMar 09 17:12:50.915[0m [34mDEBUG[0m chain: Check orphans: from 8veiAXzFM9bBvFotemJDzpcUzj3gRPmuN1y2WipvQJ4s, # orphans 0    
   0: rust_begin_unwind
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a/library/core/src/result.rs:973
   4: prometheus::vec::MetricVec<T>::with_label_values
             at /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.11.0/src/vec.rs:258
   5: near_metrics::inc_counter_vec
```
Failing after #3944

### PR DESCRIPTION
**Pull request by khorolets**
Fixes #4063 wrong usage of metrics

### CODE REVIEW

**Review by frol — APPROVED** [review]

**Review by bowenwang1996 — APPROVED** [review]

File: chain/jsonrpc-primitives/src/types/validator.rs [hunk 1]
```diff
@@ -43,10 +43,11 @@ impl From<near_client_primitives::types::GetValidatorInfoError> for RpcValidator
...
             }
-            near_client_primitives::types::GetValidatorInfoError::Unreachable(s) => {
+            near_client_primitives::types::GetValidatorInfoError::Unreachable(error_message) => {
+                tracing::warn!(target: "jsonrpc", "Unreachable error occurred: {}", &error_message);
                 near_metrics::inc_counter_vec(
                     &crate::metrics::RPC_UNREACHABLE_ERROR_COUNT,
-                    &["RpcValidatorError", &s],
+                    &["RpcValidatorError"],
                 );
                 Self::Unreachable(s)
```
Comment (frol) [inline chain/jsonrpc-primitives/src/types/validator.rs:52]:
```suggestion
                Self::Unreachable(error_message)
```
