### PR TITLE
fix: fix account deserialization on arm64 while keeping the behavior of panicking if deserializing too big a slice

### LINKED ISSUE #6293: Account deserialization fails on ARM64
**Describe the bug**

The versioning check for Account type deserialization is invalid since it compares the size of the buffer holding serialized data (72 bytes) with a memory layout size of the struct (platform-dependent due to alignment and it seems to be 72 bytes on amd64, while it is 80 bytes on arm64 [Apple M1]) instead of the size of the serialized struct.

https://github.com/near/nearcore/blob/5568df666a0f5025c724027814069050acb194c6/core/primitives-core/src/account.rs#L113-L130

cc @EgorKulikov @mm-near 

**To Reproduce**

1. Compile neard for Apple M1 (#6200 is already on master)
2. Init neard: `./target/debug/neard --home /tmp/near-home init`
3. Run neard: `./target/debug/neard --home /tmp/near-home run`

**Expected behavior**

It should deserialize the value just fine, and it does when I just remove the condition and let it deserialize the LegacyAccount struct.

image

**Version (please complete the following information):**
- nearcore commit/branch: master 5568df666a0f5025c724027814069050acb194c6
- rust version (if local): 1.58.1
- docker (if using docker): no
- mainnet/testnet/betanet/local

### PR DESCRIPTION
**Pull request by Ekleog**
Fixes #6293 

Note I'm not sure why we were panicking upon invalid buffer length before: it looks to me like something that was left over from an experiment of adding a second version of account serialization and no longer makes sense, but I'm keeping it for now until @EgorKulikov comments about its use.

I tried building and running the two neard command lines listed in #6293 on both arm64 and amd64 and they succeeded properly.

cc @frol @EgorKulikov @bowenwang1996 @mm-near

### CODE REVIEW

**Comment by matklad** [comment]
cc https://github.com/near/nearcore/issues/6186 for the panic issue.

**Comment by Ekleog** [comment]
Oh I hadn't seen that issue, thank you for the link!

File: core/primitives-core/src/account.rs [hunk 1]
```diff
@@ -112,20 +112,19 @@ struct LegacyAccount {
 
 impl BorshDeserialize for Account {
     fn deserialize(buf: &mut &[u8]) -> Result<Self, io::Error> {
-        if buf.len() == std::mem::size_of::<LegacyAccount>() {
```
Comment (matklad) [inline core/primitives-core/src/account.rs:115]: I'd just hard-coded the constant here, deserializing LegacyAccount every time feels like it can affect performance negatively. We can than have a test which compares the constant with the size of serialized account.

**Review by matklad — COMMENTED** [review]
Out of curiosity, does grepping for size_of turns out more patterns like this?

File: core/primitives-core/src/account.rs (hunk 1 above)
Comment (matklad) [reply core/primitives-core/src/account.rs:115]: Ah yes, you are completely right!

**Review by matklad — APPROVED** [review]

**Comment by Ekleog** [comment]
I could not find other patterns similar to this, the closest one I could find was https://github.com/near/nearcore/blob/master/core/primitives-core/src/hash.rs#L67 ; which doesn't suffer from the same issue as it's checking for the length only after a successful deserialization :)
