### PR TITLE
fix: Fix mac release script

### LINKED ISSUE #5953: MacOS binary release pipeline is failing
See https://github.com/near/nearcore/actions/runs/1611832093

```
mv sandbox/release/neard target/release/near-sandbox
cp: target/release/near: No such file or directory
Error: Process completed with exit code 1.
```

It looks like this is related to the removal of `near` binary target.

### PR DESCRIPTION
**Pull request by pmnoxx**
Fix error used by uploading old `near` binary in the mac script.

Closes #5953

### CODE REVIEW

**Review by nikurt — APPROVED** [review]

File: scripts/mac-release.sh [hunk 1]
```diff
@@ -31,32 +31,31 @@ function tar_binary {
...
+    then
+        aws s3 cp --acl public-read target/release/$1 s3://build.nearprotocol.com/nearcore/${os}/${branch}/${commit}/perf/$1
+        aws s3 cp --acl public-read target/release/$1 s3://build.nearprotocol.com/nearcore/${os_and_arch}/${branch}/${commit}/perf/$1
+    else
+        aws s3 cp --acl public-read target/release/$1 s3://build.nearprotocol.com/nearcore/${os}/${branch}/${commit}/nightly/$1
+        aws s3 cp --acl public-read target/release/$1 s3://build.nearprotocol.com/nearcore/${os_and_arch}/${branch}/${commit}/nightly/$1
+    fi
 }
 
-upload_binary near
```
Comment (mina86) [inline scripts/mac-release.sh:59]: There’s a lot of whitespace changes causing noise just to add this one line.

**Review by mina86 — APPROVED** [review]
